title: Mohammed Zniber # your name (or website title) here
logo: "/images/profile.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  Data Scientist with 6 years of experience in Data collection, processing, exploration, and modelling.
  <br><br>
  <a href="https://www.linkedin.com/in/zniber/">View my LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here

colors:
  crimson: '#900C3F'
